### ISSUE TITLE
when teacher is an ensemble mdoel

### ISSUE THREAD

**Issue by liangzimei** [Ujjwal-9/Knowledge-Distillation#1]
hello @Ujjwal-9  when i train a student taught by en ensemble model (two models ), the acc of student is between the two teachers, the expected result is beyond both two teachers, any suggestion? thanks in advance~

**Comment by ujjwal-9** [comment]
Are you using soft targets for calculating objective function or hard targets? **use soft targets**

If you are using **soft targets** then to improve the performance of student networks, use temperature to balance different teachers.

If student networks are provided with multiple streams of information via the various teacher distributions, the student will observe various ”views” of the data and will be able to generalize better while at the same the time it can capture different information provided by teacher networks. To facilitate this strategy **try creating multiple copies of data with corresponding soft output targets from various teachers.**

I hope this helps !

**Comment by liangzimei** [comment]
thank you @Ujjwal-9  i trained the student model as you said, now it looks good.
